apiVersion: backstage.io/v1alpha1
kind: 'Component'
metadata:
  name: backstage-techdocs
  description: "Welcome"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: 'Documentation'
  lifecycle: production
  owner: 'capabilities_enablement'
